/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpf;

import classes.Verificar_CPF;
import contato.contato;
import controle.contatoDA0;
import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Renato De Moura
 */
public class CPF_Main extends javax.swing.JFrame {
    private Object stmt;

    /**
     * Creates new form CPF_Main
     */
    public CPF_Main() {
       
        initComponents();
        setIcon();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cpf = new javax.swing.JFormattedTextField();
        verificarcpf = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        prontuario = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rg = new javax.swing.JFormattedTextField();
        sexo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cor = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        tel2 = new javax.swing.JFormattedTextField();
        pes1 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        cidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cep = new javax.swing.JFormattedTextField();
        uf = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pai = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        mae = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sangue = new javax.swing.JComboBox();
        calcular = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        txtresultado = new javax.swing.JTextField();
        limparr = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        especialidade = new javax.swing.JComboBox();
        altura = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        oi = new javax.swing.JMenu();
        limparRegistro = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        salvar = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Roberto Bolanõs");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, null, null));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        jLabel1.setText("CPF:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 100, 30, 14);

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf.setEnabled(false);
        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });
        jPanel1.add(cpf);
        cpf.setBounds(60, 100, 100, 20);

        verificarcpf.setText("...");
        verificarcpf.setEnabled(false);
        verificarcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarcpfActionPerformed(evt);
            }
        });
        verificarcpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                verificarcpfKeyPressed(evt);
            }
        });
        jPanel1.add(verificarcpf);
        verificarcpf.setBounds(180, 100, 30, 23);

        jLabel2.setText("Prontuario:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 14, 70, 14);

        try {
            prontuario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(prontuario);
        prontuario.setBounds(80, 10, 136, 20);

        jLabel3.setText("Paciente");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 60, 14);

        nome.setEnabled(false);
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeKeyTyped(evt);
            }
        });
        jPanel1.add(nome);
        nome.setBounds(70, 60, 350, 20);

        jLabel4.setText("RG:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 120, 30, 14);

        rg.setEnabled(false);
        jPanel1.add(rg);
        rg.setBounds(300, 100, 146, 20);

        sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sexo", "M", "F" }));
        sexo.setEnabled(false);
        jPanel1.add(sexo);
        sexo.setBounds(440, 60, 60, 20);

        jLabel5.setText("Raça/Cor:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(520, 60, 60, 14);

        cor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Negra", "Parda", "India", "Amarela", "Branca" }));
        cor.setEnabled(false);
        jPanel1.add(cor);
        cor.setBounds(590, 60, 64, 20);

        jLabel6.setText("Telefones:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 145, 70, 14);

        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone.setEnabled(false);
        jPanel1.add(telefone);
        telefone.setBounds(80, 140, 109, 20);

        try {
            tel2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tel2.setEnabled(false);
        tel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel2ActionPerformed(evt);
            }
        });
        jPanel1.add(tel2);
        tel2.setBounds(80, 170, 109, 20);

        pes1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Celular", "Fixo", "Comercial", "Trabalho" }));
        pes1.setEnabled(false);
        pes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pes1ActionPerformed(evt);
            }
        });
        jPanel1.add(pes1);
        pes1.setBounds(200, 140, 71, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Celular", "Fixo", "Comercial", "Trabalho" }));
        jComboBox4.setEnabled(false);
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(200, 170, 71, 20);

        jLabel7.setText("Email:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(290, 140, 40, 14);

        email.setEnabled(false);
        jPanel1.add(email);
        email.setBounds(330, 140, 271, 20);

        cidade.setEnabled(false);
        jPanel1.add(cidade);
        cidade.setBounds(80, 290, 370, 20);

        jLabel10.setText("Endereço:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 250, 60, 14);

        endereco.setEnabled(false);
        jPanel1.add(endereco);
        endereco.setBounds(80, 250, 480, 20);

        jLabel11.setText("Bairro:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 290, 40, 14);

        jLabel12.setText("CEP:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 210, 40, 14);

        try {
            cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cep.setEnabled(false);
        jPanel1.add(cep);
        cep.setBounds(80, 210, 120, 20);

        uf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        uf.setEnabled(false);
        jPanel1.add(uf);
        uf.setBounds(290, 210, 56, 20);

        jLabel13.setText("UF:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(250, 210, 17, 14);

        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("...");
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 10, 30, 23);

        jLabel18.setText("Nascimento:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(460, 100, 90, 14);

        jLabel19.setText("Pai");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 320, 60, 14);

        pai.setEnabled(false);
        jPanel1.add(pai);
        pai.setBounds(80, 320, 480, 20);

        jLabel20.setText("Mãe");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 350, 60, 14);

        mae.setEnabled(false);
        mae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maeActionPerformed(evt);
            }
        });
        jPanel1.add(mae);
        mae.setBounds(80, 350, 480, 20);

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jLabel8.setText("Tipo Sanguineo:");

        sangue.setForeground(new java.awt.Color(255, 0, 0));
        sangue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        sangue.setEnabled(false);

        calcular.setText("Calcular");
        calcular.setEnabled(false);
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        jLabel9.setText("Altura :");

        jLabel14.setText("peso:");

        jLabel15.setText("Resultado:");

        peso.setEnabled(false);

        txtresultado.setEnabled(false);
        txtresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresultadoActionPerformed(evt);
            }
        });

        limparr.setText("limpar");
        limparr.setEnabled(false);
        limparr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparrActionPerformed(evt);
            }
        });

        jLabel16.setText("Dia da Consulta:");

        especialidade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        especialidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ESPECIALIDADE MÉDICA", "Anatomia Patológica", "Anestesiologia", "Angiologia e Cirurgia Vascular", "Cardiologia", "Cardiologia Pediátrica", "Cirurgia Cardiotorácica", "Cirurgia Geral", "Cirurgia Maxilo-Facial", "Cirurgia Pediátrica", "Cirurgia Plástica Reconstrutiva e Estética", "Dermato-Venereologia", "Doenças Infecciosas", "Endocrinologia e Nutrição", "Estomatologia", "Gastrenterologia", "Genética Médica", "Ginecologia/Obstetrícia", "Imunoalergologia", "Imunohemoterapia", "Farmacologia Clínica", "Hematologia Clínica", "Medicina Desportiva", "Medicina do Trabalho", "Medicina Física e de Reabilitação", "Medicina Geral e Familiar", "Medicina Interna", "Medicina Legal", "Medicina Nuclear", "Medicina Tropical", "Nefrologia", "Neurocirurgia", "Neurologia", "Neurorradiologia", "Oftalmologia", "Oncologia Médica", "Ortopedia", "Otorrinolaringologia", "Patologia Clínica", "Pediatria", "Pneumologia", "Psiquiatria", "Psiquiatria da Infância e da Adolescência", "Radiologia", "Radioncologia", "Reumatologia", "Saúde Pública", "Urologia" }));
        especialidade.setEnabled(false);

        try {
            altura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        altura.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sangue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(calcular)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limparr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(828, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sangue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcular)
                    .addComponent(limparr)
                    .addComponent(jLabel15)
                    .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        jLabel17.setText("Hospital Robeto Bolanõs é uma omenagem para um dos maiores comediantes. Programa desenvolvido em Java com IDE Netbeans... Todos os direitos autorais estão resevardos.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(616, 616, 616))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(549, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sobre", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("Novo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jRadioButtonMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Novo Cadastro");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu1);

        oi.setText("Limpar");
        oi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oiActionPerformed(evt);
            }
        });

        limparRegistro.setSelected(true);
        limparRegistro.setText("Limpar Registro");
        limparRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/clear.png"))); // NOI18N
        limparRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparRegistroActionPerformed(evt);
            }
        });
        oi.add(limparRegistro);

        jMenuBar1.add(oi);

        jMenu2.setText("Sair");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("SALVAR");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        salvar.setSelected(true);
        salvar.setText("SALVAR");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        jMenu3.add(salvar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Botao sair topo
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void limparrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparrActionPerformed
        // botao limpar altura e peso
        txtresultado.setText("");
        peso.setText("");
        altura.setText("");
    }//GEN-LAST:event_limparrActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // botao calcualr....
         
        double num1 = Double.parseDouble(peso.getText());
        double num2 = Double.parseDouble(altura.getText());
        double res=(num1/(num2*num2));
        txtresultado.setText(String.valueOf(res));
       
        if(res<18.5){
        
            JOptionPane.showMessageDialog(null,"O Paciente estar ABAIXO DO PESO IDEAL!");
    
    }
    }//GEN-LAST:event_calcularActionPerformed

    private void pes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pes1ActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void verificarcpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarcpfKeyPressed
        // TODO add your handling code here:
        try{
            verificar();

        }
        catch (Exception e){
            e.getMessage();
        }

    }//GEN-LAST:event_verificarcpfKeyPressed

    private void verificarcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarcpfActionPerformed
        // TODO add your handling code here:
        try{
            verificar();

        }
        catch(Exception e){
            e.getMessage();
        }

    }//GEN-LAST:event_verificarcpfActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    private void oiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oiActionPerformed
        // botao limpar geral....
           
    }//GEN-LAST:event_oiActionPerformed

    private void tel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // botao EM BRANCO AINDA.....
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // BOTAO NOVO ACESSAR TUDO...
        nome.setEnabled(true);
        cpf.setEnabled(true);
        endereco.setEnabled(true);
        email.setEnabled(true);
        cidade.setEnabled(true);
        telefone.setEnabled(true);
        tel2.setEnabled(true);
        rg.setEnabled(true);
        verificarcpf.setEnabled(true);
        sexo.setEnabled(true);
        cor.setEnabled(true);
        pes1.setEnabled(true);
        cep.setEnabled(true);
        sangue.setEnabled(true);
        altura.setEnabled(true);
        peso.setEnabled(true);
        calcular.setEnabled(true);
        limparr.setEnabled(true);
        
        especialidade.setEnabled(true);
        txtresultado.setEnabled(true);
       
        
        
        
        
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void limparRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparRegistroActionPerformed
        // limpar gegistro... tuddooooo
        nome.setText("");
        prontuario.setText("");
        cpf.setText("");
        endereco.setText("");
        email.setText("");
        cidade.setText("");
        telefone.setText("");
        tel2.setText("");
        rg.setText("");
        cep.setText("");
       
        
        
        
    }//GEN-LAST:event_limparRegistroActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
//BOTAO SALVAR... nome, endereco, cpf, rg, cep, cidade, logradore, pai , mae, telefone, email, prontuario,sexo
        try {
        contato cl = new contato();
        cl.setNome(nome.getText());
        cl.setEndereco(endereco.getText());
        cl.setCpf(cpf.getText());
        cl.setCidade(rg.getText());
        cl.setCep(cep.getText());
        cl.setCidade(cidade.getText());
        cl.setPai(pai.getText());
        cl.setMae(mae.getText());
        cl.setTelefone(telefone.getText());
        cl.setEmail(email.getText());
        cl.setProntuario(prontuario.getText());
        cl.setSexo(sexo.getUIClassID());
        
        
            contatoDA0 dao = new contatoDA0();
            dao.adicionar(cl);
        } catch (SQLException ex) {
            Logger.getLogger(CPF_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
          
            
            
     
    }//GEN-LAST:event_salvarActionPerformed

    private void nomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeKeyTyped

    }//GEN-LAST:event_nomeKeyTyped

    private void txtresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresultadoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtresultadoActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void maeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CPF_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CPF_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CPF_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CPF_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CPF_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField altura;
    private javax.swing.JButton calcular;
    private javax.swing.JFormattedTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JComboBox cor;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endereco;
    private javax.swing.JComboBox especialidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButtonMenuItem limparRegistro;
    private javax.swing.JButton limparr;
    private javax.swing.JTextField mae;
    private javax.swing.JTextField nome;
    private javax.swing.JMenu oi;
    private javax.swing.JTextField pai;
    private javax.swing.JComboBox pes1;
    private javax.swing.JTextField peso;
    private javax.swing.JFormattedTextField prontuario;
    private javax.swing.JFormattedTextField rg;
    private javax.swing.JRadioButtonMenuItem salvar;
    private javax.swing.JComboBox sangue;
    private javax.swing.JComboBox sexo;
    private javax.swing.JFormattedTextField tel2;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JTextField txtresultado;
    private javax.swing.JComboBox uf;
    private javax.swing.JButton verificarcpf;
    // End of variables declaration//GEN-END:variables

    public void verificar(){
  
        try{
        String cpf =cpf.getText();
        
        Verificar_CPF documento = new Verificar_CPF();
        documento.setCpf(cpf);
        documento.verificando();
        
        cpf.setText("");
          
    }
        catch(Exception e){
        e.getMessage();
        
      
    }



}

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("doutor icone.png"))) ;
    }


}// FIM DOS JOGOS.... VC AINDA TA VIVO...