/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tlogin;

/**
 *
 * @author G0011216
 */
public class Telaprincipal extends javax.swing.JFrame {

    /**
     * Creates new form Telaprincipal
     */
    public Telaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jcadastroCliente = new javax.swing.JMenuItem();
        jcadastroMedico = new javax.swing.JMenuItem();
        jcadastroUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrame1.setTitle("BEM VINDO AO SISTEMA DE SAÚDE");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/patient_chart.png"))); // NOI18N
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 60, 110, 110);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(280, 60, 110, 110);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ecg_chart.png"))); // NOI18N
        jPanel1.add(jButton3);
        jButton3.setBounds(140, 60, 110, 110);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/doctor.png"))); // NOI18N
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 60, 110, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/08037441853966317028929046847442474.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, -40, 1240, 340);

        jInternalFrame1.getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 1240, 370);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 70, 1280, 410);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/08037441853966317028929046847442474.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 0, 1080, 450);

        jMenu1.setText("Cadastro");

        jcadastroCliente.setText("Cadastro de cliente");
        jMenu1.add(jcadastroCliente);

        jcadastroMedico.setText("Cadastro de Médico");
        jMenu1.add(jcadastroMedico);

        jcadastroUsuario.setText("Cadastro de Usuario");
        jMenu1.add(jcadastroUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Marcaçao Consulta");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatorio Medico");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1299, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jcadastroCliente;
    private javax.swing.JMenuItem jcadastroMedico;
    private javax.swing.JMenuItem jcadastroUsuario;
    // End of variables declaration//GEN-END:variables
}
